### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TrickJoker312** [interstellarnetwork/interstellar-v3#46]
### What is this request?

New game

### Please describe the new feature here

Hey! I was wondering if you could add the Lofi Funkin mod from the Friday Night Funkin game? I'd really appreciate it!

**Comment by imbubbo** [comment]
For v3 or v4

**Comment by TrickJoker312** [comment]
Thank you! I appreciate it!

**Comment by TrickJoker312** [comment]
[also, when is v3?]

**Comment by imbubbo** [comment]
??
